// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: log.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type LogORM struct {
	Address          string `gorm:"index:idx_address"`
	BlockHash        string
	BlockNumber      uint64 `gorm:"index:idx_block_number"`
	BlockTimestamp   uint64
	Data             string
	Id               uint64
	Indexed          string
	ItemId           string
	ItemTimestamp    string
	LogIndex         uint64
	TransactionHash  string `gorm:"index:idx_transaction_hash"`
	TransactionIndex uint32
	Type             string
}

// TableName overrides the default tablename generated by GORM
func (LogORM) TableName() string {
	return "logs"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *Log) ToORM(ctx context.Context) (LogORM, error) {
	to := LogORM{}
	var err error
	if prehook, ok := interface{}(m).(LogWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Type = m.Type
	to.LogIndex = m.LogIndex
	to.TransactionHash = m.TransactionHash
	to.TransactionIndex = m.TransactionIndex
	to.Address = m.Address
	to.Data = m.Data
	to.Indexed = m.Indexed
	to.BlockNumber = m.BlockNumber
	to.BlockTimestamp = m.BlockTimestamp
	to.BlockHash = m.BlockHash
	to.ItemId = m.ItemId
	to.ItemTimestamp = m.ItemTimestamp
	to.Id = m.Id
	if posthook, ok := interface{}(m).(LogWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *LogORM) ToPB(ctx context.Context) (Log, error) {
	to := Log{}
	var err error
	if prehook, ok := interface{}(m).(LogWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Type = m.Type
	to.LogIndex = m.LogIndex
	to.TransactionHash = m.TransactionHash
	to.TransactionIndex = m.TransactionIndex
	to.Address = m.Address
	to.Data = m.Data
	to.Indexed = m.Indexed
	to.BlockNumber = m.BlockNumber
	to.BlockTimestamp = m.BlockTimestamp
	to.BlockHash = m.BlockHash
	to.ItemId = m.ItemId
	to.ItemTimestamp = m.ItemTimestamp
	to.Id = m.Id
	if posthook, ok := interface{}(m).(LogWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type Log the arg will be the target, the caller the one being converted from

// LogBeforeToORM called before default ToORM code
type LogWithBeforeToORM interface {
	BeforeToORM(context.Context, *LogORM) error
}

// LogAfterToORM called after default ToORM code
type LogWithAfterToORM interface {
	AfterToORM(context.Context, *LogORM) error
}

// LogBeforeToPB called before default ToPB code
type LogWithBeforeToPB interface {
	BeforeToPB(context.Context, *Log) error
}

// LogAfterToPB called after default ToPB code
type LogWithAfterToPB interface {
	AfterToPB(context.Context, *Log) error
}

// DefaultCreateLog executes a basic gorm create call
func DefaultCreateLog(ctx context.Context, in *Log, db *gorm1.DB) (*Log, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type LogORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultReadLog executes a basic gorm read call
func DefaultReadLog(ctx context.Context, in *Log, db *gorm1.DB) (*Log, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Id == 0 {
		return nil, errors1.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if db, err = gorm2.ApplyFieldSelection(ctx, db, nil, &LogORM{}); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := LogORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(LogORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type LogORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm1.DB) error
}

func DefaultDeleteLog(ctx context.Context, in *Log, db *gorm1.DB) error {
	if in == nil {
		return errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Id == 0 {
		return errors1.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&LogORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type LogORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm1.DB) error
}

func DefaultDeleteLogSet(ctx context.Context, in []*Log, db *gorm1.DB) error {
	if in == nil {
		return errors1.NilArgumentError
	}
	var err error
	keys := []uint64{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Id == 0 {
			return errors1.EmptyIdError
		}
		keys = append(keys, ormObj.Id)
	}
	if hook, ok := (interface{}(&LogORM{})).(LogORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	err = db.Where("id in (?)", keys).Delete(&LogORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&LogORM{})).(LogORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type LogORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*Log, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*Log, *gorm1.DB) error
}

// DefaultStrictUpdateLog clears / replaces / appends first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateLog(ctx context.Context, in *Log, db *gorm1.DB) (*Log, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateLog")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	lockedRow := &LogORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("id=?", ormObj.Id).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type LogORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm1.DB) error
}

// DefaultPatchLog executes a basic gorm update call with patch behavior
func DefaultPatchLog(ctx context.Context, in *Log, updateMask *field_mask1.FieldMask, db *gorm1.DB) (*Log, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	var pbObj Log
	var err error
	if hook, ok := interface{}(&pbObj).(LogWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbReadRes, err := DefaultReadLog(ctx, &Log{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	pbObj = *pbReadRes
	if hook, ok := interface{}(&pbObj).(LogWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskLog(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(LogWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateLog(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(LogWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type LogWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *Log, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type LogWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *Log, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type LogWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *Log, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type LogWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *Log, *field_mask1.FieldMask, *gorm1.DB) error
}

// DefaultPatchSetLog executes a bulk gorm update call with patch behavior
func DefaultPatchSetLog(ctx context.Context, objects []*Log, updateMasks []*field_mask1.FieldMask, db *gorm1.DB) ([]*Log, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors1.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*Log, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchLog(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskLog patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskLog(ctx context.Context, patchee *Log, patcher *Log, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*Log, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Type" {
			patchee.Type = patcher.Type
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"TransactionIndex" {
			patchee.TransactionIndex = patcher.TransactionIndex
			continue
		}
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"Data" {
			patchee.Data = patcher.Data
			continue
		}
		if f == prefix+"Indexed" {
			patchee.Indexed = patcher.Indexed
			continue
		}
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
		if f == prefix+"BlockTimestamp" {
			patchee.BlockTimestamp = patcher.BlockTimestamp
			continue
		}
		if f == prefix+"BlockHash" {
			patchee.BlockHash = patcher.BlockHash
			continue
		}
		if f == prefix+"ItemId" {
			patchee.ItemId = patcher.ItemId
			continue
		}
		if f == prefix+"ItemTimestamp" {
			patchee.ItemTimestamp = patcher.ItemTimestamp
			continue
		}
		if f == prefix+"Id" {
			patchee.Id = patcher.Id
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListLog executes a gorm list call
func DefaultListLog(ctx context.Context, db *gorm1.DB) ([]*Log, error) {
	in := Log{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &LogORM{}, &Log{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("id")
	ormResponse := []LogORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*Log{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type LogORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]LogORM) error
}
