// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: log_count_by_address.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type LogCountByAddressORM struct {
	Address         string `gorm:"index:log_count_by_address_idx_address"`
	Id              uint64
	LogIndex        uint64 `gorm:"index:log_count_by_address_idx_log_index"`
	TransactionHash string `gorm:"index:log_count_by_address_idx_transaction_hash"`
}

// TableName overrides the default tablename generated by GORM
func (LogCountByAddressORM) TableName() string {
	return "log_count_by_addresses"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *LogCountByAddress) ToORM(ctx context.Context) (LogCountByAddressORM, error) {
	to := LogCountByAddressORM{}
	var err error
	if prehook, ok := interface{}(m).(LogCountByAddressWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.LogIndex = m.LogIndex
	to.TransactionHash = m.TransactionHash
	to.Address = m.Address
	to.Id = m.Id
	if posthook, ok := interface{}(m).(LogCountByAddressWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *LogCountByAddressORM) ToPB(ctx context.Context) (LogCountByAddress, error) {
	to := LogCountByAddress{}
	var err error
	if prehook, ok := interface{}(m).(LogCountByAddressWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.LogIndex = m.LogIndex
	to.TransactionHash = m.TransactionHash
	to.Address = m.Address
	to.Id = m.Id
	if posthook, ok := interface{}(m).(LogCountByAddressWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type LogCountByAddress the arg will be the target, the caller the one being converted from

// LogCountByAddressBeforeToORM called before default ToORM code
type LogCountByAddressWithBeforeToORM interface {
	BeforeToORM(context.Context, *LogCountByAddressORM) error
}

// LogCountByAddressAfterToORM called after default ToORM code
type LogCountByAddressWithAfterToORM interface {
	AfterToORM(context.Context, *LogCountByAddressORM) error
}

// LogCountByAddressBeforeToPB called before default ToPB code
type LogCountByAddressWithBeforeToPB interface {
	BeforeToPB(context.Context, *LogCountByAddress) error
}

// LogCountByAddressAfterToPB called after default ToPB code
type LogCountByAddressWithAfterToPB interface {
	AfterToPB(context.Context, *LogCountByAddress) error
}

// DefaultCreateLogCountByAddress executes a basic gorm create call
func DefaultCreateLogCountByAddress(ctx context.Context, in *LogCountByAddress, db *gorm1.DB) (*LogCountByAddress, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type LogCountByAddressORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultReadLogCountByAddress executes a basic gorm read call
func DefaultReadLogCountByAddress(ctx context.Context, in *LogCountByAddress, db *gorm1.DB) (*LogCountByAddress, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Id == 0 {
		return nil, errors1.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if db, err = gorm2.ApplyFieldSelection(ctx, db, nil, &LogCountByAddressORM{}); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := LogCountByAddressORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(LogCountByAddressORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type LogCountByAddressORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm1.DB) error
}

func DefaultDeleteLogCountByAddress(ctx context.Context, in *LogCountByAddress, db *gorm1.DB) error {
	if in == nil {
		return errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Id == 0 {
		return errors1.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&LogCountByAddressORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type LogCountByAddressORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm1.DB) error
}

func DefaultDeleteLogCountByAddressSet(ctx context.Context, in []*LogCountByAddress, db *gorm1.DB) error {
	if in == nil {
		return errors1.NilArgumentError
	}
	var err error
	keys := []uint64{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Id == 0 {
			return errors1.EmptyIdError
		}
		keys = append(keys, ormObj.Id)
	}
	if hook, ok := (interface{}(&LogCountByAddressORM{})).(LogCountByAddressORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	err = db.Where("id in (?)", keys).Delete(&LogCountByAddressORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&LogCountByAddressORM{})).(LogCountByAddressORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type LogCountByAddressORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*LogCountByAddress, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*LogCountByAddress, *gorm1.DB) error
}

// DefaultStrictUpdateLogCountByAddress clears / replaces / appends first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateLogCountByAddress(ctx context.Context, in *LogCountByAddress, db *gorm1.DB) (*LogCountByAddress, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateLogCountByAddress")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	lockedRow := &LogCountByAddressORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("id=?", ormObj.Id).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type LogCountByAddressORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm1.DB) error
}

// DefaultPatchLogCountByAddress executes a basic gorm update call with patch behavior
func DefaultPatchLogCountByAddress(ctx context.Context, in *LogCountByAddress, updateMask *field_mask1.FieldMask, db *gorm1.DB) (*LogCountByAddress, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	var pbObj LogCountByAddress
	var err error
	if hook, ok := interface{}(&pbObj).(LogCountByAddressWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbReadRes, err := DefaultReadLogCountByAddress(ctx, &LogCountByAddress{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	pbObj = *pbReadRes
	if hook, ok := interface{}(&pbObj).(LogCountByAddressWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskLogCountByAddress(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(LogCountByAddressWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateLogCountByAddress(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(LogCountByAddressWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type LogCountByAddressWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *LogCountByAddress, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *LogCountByAddress, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *LogCountByAddress, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *LogCountByAddress, *field_mask1.FieldMask, *gorm1.DB) error
}

// DefaultPatchSetLogCountByAddress executes a bulk gorm update call with patch behavior
func DefaultPatchSetLogCountByAddress(ctx context.Context, objects []*LogCountByAddress, updateMasks []*field_mask1.FieldMask, db *gorm1.DB) ([]*LogCountByAddress, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors1.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*LogCountByAddress, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchLogCountByAddress(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskLogCountByAddress patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskLogCountByAddress(ctx context.Context, patchee *LogCountByAddress, patcher *LogCountByAddress, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*LogCountByAddress, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"Id" {
			patchee.Id = patcher.Id
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListLogCountByAddress executes a gorm list call
func DefaultListLogCountByAddress(ctx context.Context, db *gorm1.DB) ([]*LogCountByAddress, error) {
	in := LogCountByAddress{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &LogCountByAddressORM{}, &LogCountByAddress{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("id")
	ormResponse := []LogCountByAddressORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByAddressORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*LogCountByAddress{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type LogCountByAddressORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByAddressORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]LogCountByAddressORM) error
}
