// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: log_ws.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type LogWebsocketIndexORM struct {
	LogIndex        uint64 `gorm:"primary_key"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (LogWebsocketIndexORM) TableName() string {
	return "log_websocket_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *LogWebsocketIndex) ToORM(ctx context.Context) (LogWebsocketIndexORM, error) {
	to := LogWebsocketIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(LogWebsocketIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.LogIndex = m.LogIndex
	to.TransactionHash = m.TransactionHash
	if posthook, ok := interface{}(m).(LogWebsocketIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *LogWebsocketIndexORM) ToPB(ctx context.Context) (LogWebsocketIndex, error) {
	to := LogWebsocketIndex{}
	var err error
	if prehook, ok := interface{}(m).(LogWebsocketIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.LogIndex = m.LogIndex
	to.TransactionHash = m.TransactionHash
	if posthook, ok := interface{}(m).(LogWebsocketIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type LogWebsocketIndex the arg will be the target, the caller the one being converted from

// LogWebsocketIndexBeforeToORM called before default ToORM code
type LogWebsocketIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *LogWebsocketIndexORM) error
}

// LogWebsocketIndexAfterToORM called after default ToORM code
type LogWebsocketIndexWithAfterToORM interface {
	AfterToORM(context.Context, *LogWebsocketIndexORM) error
}

// LogWebsocketIndexBeforeToPB called before default ToPB code
type LogWebsocketIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *LogWebsocketIndex) error
}

// LogWebsocketIndexAfterToPB called after default ToPB code
type LogWebsocketIndexWithAfterToPB interface {
	AfterToPB(context.Context, *LogWebsocketIndex) error
}

// DefaultCreateLogWebsocketIndex executes a basic gorm create call
func DefaultCreateLogWebsocketIndex(ctx context.Context, in *LogWebsocketIndex, db *gorm1.DB) (*LogWebsocketIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogWebsocketIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogWebsocketIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type LogWebsocketIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogWebsocketIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskLogWebsocketIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskLogWebsocketIndex(ctx context.Context, patchee *LogWebsocketIndex, patcher *LogWebsocketIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*LogWebsocketIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListLogWebsocketIndex executes a gorm list call
func DefaultListLogWebsocketIndex(ctx context.Context, db *gorm1.DB) ([]*LogWebsocketIndex, error) {
	in := LogWebsocketIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogWebsocketIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &LogWebsocketIndexORM{}, &LogWebsocketIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogWebsocketIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("log_index")
	ormResponse := []LogWebsocketIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogWebsocketIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*LogWebsocketIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type LogWebsocketIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogWebsocketIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogWebsocketIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]LogWebsocketIndexORM) error
}
